---
title: "Assignments"
slug: assignments
---

## Grade Calculator

- [<i class="fas fa-calculator"></i> `Grade Calculator`](https://ryansafner.shinyapps.io/480_grade_calculator/)

Use this tool to calculate your final course grade and predict what grades you would need on remaining assignments to obtain a desired course grade.

# Problem Sets

There will be several problem sets (one at the end of each lesson). Problem sets will be a combination of math/statistical theory & application problems and problems that require use of R with real data. You may collaborate with other students to work on problem sets, but *each person must turn in an individual problem set*. Problem sets are due *one week* from the class period where we finish a lesson, and must *emailed* to me by the start of class (so please type or, if you must, hand write and scan them). 

# Midterm

After we have finished linear regression, there will be a midterm constituting a combination of multiple choice, problem, and short answer questions. This will cover the content we discuss in class, my lectures, and the readings. The midterm provides feedback both to you and to me that ensures everyone is progressing on schedule and comprehending the material. This is *critical*, as the rest of the course will build off of this foundation. 

# Final

On the college-determined date, we will have a comprehensive, closed-book, in-class final exam. 

# Empirical Research Paper 

- [<i class="fas fa-laptop-code"> See Description</i>](/assignment/paper-project)

You are required to write a short research paper any topic in political economy of your choosing, so long as it has an econometric component (at minimum, features a linear regression). I expect your topic and your findings to be very rudimentary (your results do not need to be significant). The main purpose of this paper is to walk you through the process of conducting research and using econometrics to gain insight on a problem. The most difficult part of this assignment is finding appropriate and sufficient data. I will discuss more about this paper at length in class, and briefly guide you through the craft of writing a good paper. I view this assignment as the primary demonstration of your mastery of this class, and writing is a marketable skill you will need for any gainful employment. I strongly recommend starting early and discussing your topics with me, but this is not required. On the final week of class, we will hold a workshop for each of you to give a short presentation of your paper, and for everyone to provide comments and constructive criticism to help you improve and complete your paper.
