---
title: "Schedule"
slug: schedule
---

This page contains all of the following resources for each class meeting: 

- <i class="fas fa-book-reader"></i> **Readings** include textbook chapters and occasional journal articles
- <i class="fas fa-laptop-code"></i> **Assignments** are due by the beginning of class unless otherwise stated
- <i class="fas fa-info-circle"></i> **Class** materials contain more details, math appendices, and other helpful resources^[These "online appendices" keep the slides nice and de-cluttered!]
- <i class="fas fa-chalkboard-teacher"></i> **Slides** are "[Xaringan](https://github.com/yihui/xaringan)" presentations in html that can be opened in any browser^[You can find a downloadable <i class="fas fa-file-pdf"></i> `PDF` in each respective <i class="fas fa-info-circle"></i> **class** page]
- <i class="fas fa-registered"></i> **R** materials contain extra tutorials, videos, practice exercises for using `R`

Relevant materials (if applicable, icons will become links) will be posted before class meets.

**Last Update**: [`r format(Sys.time(), "%X %a %b %d %Y")`](https://github.com/ryansafner/metricsF20/commits/master)

---

`r blogdown::shortcode("schedule")`
