---
title: "Final Review Questions"
subtitle: "ECON 480 • Econometrics • Fall 2020"
author: 'Ryan Safner<br> Assistant Professor of Economics <br> <a href="mailto:safner@hood.edu"><i class="fa fa-paper-plane fa-fw"></i>safner@hood.edu</a> <br> <a href="https://github.com/ryansafner/metricsF20"><i class="fa fa-github fa-fw"></i>ryansafner/metricsF20</a><br> <a href="https://metricsF20.classes.ryansafner.com"> <i class="fa fa-globe fa-fw"></i>metricsF20.classes.ryansafner.com</a><br>'
#date:
output:
  xaringan::moon_reader:
    mathjax: "https://cdn.bootcss.com/mathjax/2.7.1/MathJax.js?config=TeX-MML-AM_HTMLorMML" # rescales math with css changes https://github.com/yihui/xaringan/issues/143
    lib_dir: libs
    df_print: paged
    css: [custom.css, "hygge"] #, metropolis, metropolis-fonts
    nature:
      beforeInit: ["macros.js", "https://platform.twitter.com/widgets.js"] # first is for rescaling images , second is for embedding tweets, https://github.com/yihui/xaringan/issues/100
      highlightStyle: github
      highlightLines: true
      countIncrementalSlides: false
      ratio: "16:9"
      slideNumberFormat: |
        <div class="progress-bar-container">
          <div class="progress-bar" style="width: calc(%current% / %total% * 100%);">
          </div>
        </div>
    includes:
      in_header: header.html # for font awesome, used in title  
---

```{r setup, include=FALSE}
options(htmltools.dir.version = FALSE)
knitr::opts_chunk$set(echo=F,
                      message=F,
                      warning=F)
library(tidyverse)
set.seed(256)
update_geom_defaults("label", list(family = "Fira Sans Condensed"))
```

# Major Models and Extensions

- Causality
  - Fundamental problem of causal inference
  - DAGs, controlling

--

- Multivariate OLS
  - Omitted Variable Bias
  - Variance/Multicollinearity

--

- Categorical data
  - Using categorical variables as dummies
  - dummy variable trap
  - interaction effects

---

# Major Models and Extensions

- Nonlinear Models
  - quadratic model, polynomial models, logarithmic models

--

- Panel Data
  - pooled model
  - fixed effects
  - difference-in-difference models

---

# Question 1

What are the two conditions for a variable $Z$ to cause .shout[omitted variable bias] if it is left out of the regression?

---

# Question 2

$$\widehat{Wages}_i=\beta_0+\beta_1 \, Education_i + \beta_2 \, Age_i + \beta_3 \, Experience_i + \epsilon_i$$

Suppose $Education_i$ and $Age_i$ are highly correlated

--

- Does this .hi-purple[bias] $\hat{\beta_1}$ and $\hat{\beta_2}$?

--

- What will happen to the .hi-purple[variance] of $\hat{\beta_2}$ and $\hat{\beta_2}$? How can we measure this? 

---

# Question 3

$$\widehat{Cholesterol_i}=\beta_0+\beta_1 \, Treated_i+u_i$$

- $Treated_i$ is a dummy variable $\begin{cases} =1 & \text{if person received treatment}\\ =0 & \text{if person did not receive treatment}\\ \end{cases}$

--
- What is $\hat{\beta_0}$?

--

- What is $\hat{\beta_1}$?

--

- What is the average cholesterol level for someone who recieved treatment? 

---

# Question 4

$$\widehat{Y}_i=\beta_0+\beta_1 \, Red_i+\beta_2 \, Orange_i+\beta_3 \, Yellow_i+\beta_4 \, Green_i+\beta_5 \, Blue_i$$

Suppose observation $i$ can be either $\{$Red, Orange, Yellow, Green, Blue, Purple $\}$

--

- What is $\hat{\beta_0}$?

--

- What is $\hat{\beta_1}$?

--

- What is the average value of $Y_i$ for $Green$ shapes?

--

- Why can't we add $\beta_6 \, Purple_i$?

---

# Question 5

$$\widehat{Utility}_i=\beta_0+\beta_1 \, Eggs_i+\beta_2 \, Breakfast_i+\beta_3 (Eggs_i \times Breakfast_i)$$

$Breakfast_i$ is a dummy variable $\begin{cases} =1 & \text{if meal i is breakfast}\\ =0 & \text{if meal i is not breakfast}\\ \end{cases}$

--

- What is $\hat{\beta_1}$?

--

- What is $\hat{\beta_2}$?

--

- What is $\hat{\beta_3}$?

--

- We have two regressions (one for Breakfast; one for Not Breakfast)
    - how can we determine if the intercepts are different?
    - how can we determine if the slopes are different?

---

# Question 6


$$\widehat{Utility}=2+4\text{ Ice Cream Cones}_i-1\text{ Ice Cream Cones}_i^2$$

--

- What is the marginal effect of eating 1 more Ice Cream Cone?

--

- What if we *start* with 1 Ice Cream Cone?

--

- What if we *start* with 4 Ice Cream Cones?
--

- What amount of ice cream cones will *maximize* utility?

--

- How would we know if we should add $\text{Ice Cream Cones}_i^3$?

---

# Question 7

$$ln(GDP_i)=10+2\text{ population (in billions)}_i$$

- Interpret $\hat{\beta_1}$ in context.

--

$$ln(GDP_i)=10+0.1 \, ln(\text{population}_i)$$

- Interpret $\hat{\beta_1}$ in context.

---

# Question 8

- Explain what an $F$-test is used for

--

- Explain *how* an $F$-statistic is generated

---

# Question 9

$$\widehat{\text{Divorce Rate}_{it}}=\beta_0+\beta_1 \text{Divorce Law}_{it}+\alpha_i+\theta_t+\epsilon_{it}$$

--

- Why do we need $\alpha_i$ and $\theta_t$?

--

- What sorts of things are in $\alpha_i$?

--

- What sorts of things are in $\theta_t$? 

---

# Question 10

$$\widehat{\text{Crime Rate}_{it}}=\beta_0+\beta_1 \, \text{Maryland}_{i}+\beta_2 \, \text{After}_t+\beta_3  \, (\text{Maryland}_i \times \text{After}_t)$$

- Suppose Maryland passes a law (and other States do not) that affects crime rates

--

- What must we assume about Maryland over time?

--

- What is the average crime rate for other states before the law?

--

- What is the average crime rate for Maryland after the law?

--

- What is the *causal effect* of passing the law?
