---
title: "1.5 —Optimize Your Workflow: Markdown, Projects, and Git - Class Notes"
citeproc: false
bibliography: ../../static/bib/references.bib
csl: ../../static/bib/chicago-syllabus-no-bib.csl
output:
  blogdown::html_page:
    template: ../../pandoc/toc-title_html.template
    toc: true
editor_options: 
  chunk_output_type: console
---

*Tuesday, September 1, 2020*

# Overview

Today I will give you about half the class period to finish your [1.4 practice problems](/practice/1.4-practice) and I can answer questions. Then I will briefly show you how you the magic of how you can improve your workflow, efficiency, automation, reproduciblity, and safe file backups with R Markdown, R Projects, git and github. All of these tools are slightly advanced, and *optional* for you to use, but the learning curve pays off very high returns for the rest of your life! A good handful of people every semester tell me that they keep using these tools years in the future.

# Readings

Please see [today's readings](/reading/1.5-reading) for more information, resources, cheetsheets, and tips.

# Slides

- [<i class="fas fa-chalkboard-teacher"></i> View Lecture Slides](/slides/1.5-slides.html)
- [<i class="fas fa-file-pdf"></i> Download as PDF](/slides/1.5-slides.pdf)

# Live Class Session on Zoom

The live class <i class="fas fa-video"></i> Zoom meeting link can be found on Blackboard (see `LIVE ZOOM MEETINGS` on the left navigation menu), starting at 11:30 AM.

If you are unable to join today's live session, or if you want to review, you can find the recording stored on Blackboard via Panopto (see `Class Recordings` on the left navigation menu).

# Practice Problems

The answer keys (in various formats) to [last class’s practice problems](/practice/1.4-r-practice) are posted on that page. Today’s "[practice problems](/r/1.5-r-practice.html)" get you to practice the tools we are working with today. They are again not required, but will help you if you are interested.

# Problem Set

[Problem Set 1](/assignment/01-problem-set.html) is posted and is due by 11:59 PM Sunday September 6 by upload on Blackboard. Please see that page for more information on how to submit (there are multiple ways!).

