---
title: "3.2 — Causal Inference & DAGS — Class Notes"
citeproc: false
bibliography: ../../static/bib/references.bib
csl: ../../static/bib/chicago-syllabus-no-bib.csl
output:
  blogdown::html_page:
    template: ../../pandoc/toc-title_html.template
    toc: true
editor_options: 
  chunk_output_type: console
---

*Thursday, October 8, 2020*

# Overview

Today we begin extending the foundation of simple linear regression with one variable into more advanced models that can plausibly claim (when we are done) to measure *causal* relationships between $X$ and $Y$. The rest of the semester is primarily extending regression from one $X$ to many, and changing the functional form to fit various idiosyncracies of different variables, or use clever techniques to isolate marginal effects of interest.

We begin by covering the fundamental problem of causal inference, that we can never observe counterfactual states of the world. If we *could*, then we could easily measure the causal effect of $X \mapsto Y$ by comparing how $Y$ is different when $X$ is different. The next best thing we can do is run a **random control trial (RCT)** where individuals are *randomly* assigned to groups to be given (different) treatment(s), and then we can compare the average outcome across groups. Random assignment ensures the only thing that differs across group outcomes is whether or not the group was given treatment, estimating the *causal effect* of treatment on the outcome. 

For now, we will understand causality to mean the average treatment effect (ATE) from a RCT. RCTs are both popular and controversial. Last year’s Nobel Prize winners in economics won for their use of RCTs in development economics, but they have drawn significant criticism from other top economists as not being sufficiently generalizable.

Of course, the bigger problem is it is very difficult, often impossible, to run a RCT to test a hypothesis. So economists have developed a toolkit of clever techniques to identify causal effects in “natural experiments” or “quasi-experiments” that sufficiently *simulate* a RCT. Knowledge of this repertoire of tools is truly why modern economists are in demand by government and business (not supply and demand models, etc)!

# Readings

Please see [today’s suggested readings](/reading/3.2-reading). There are a number of useful readings (in addition to your textbook) that can help you understand the material for today. 

# Slides

- [<i class="fas fa-chalkboard-teacher"></i> View Lecture Slides](/slides/3.2-slides.html)
- [<i class="fas fa-file-pdf"></i> Download as PDF](/slides/3.2-slides.pdf)

# Practice

See today’s [practice problems](/r/3.2-r/practice). Answers will be posted later.

# Live Class Session on Zoom

The live class <i class="fas fa-video"></i> Zoom meeting link can be found on Blackboard (see `LIVE ZOOM MEETINGS` on the left navigation menu), starting at 11:30 AM.

If you are unable to join today's live session, or if you want to review, you can find the recording stored on Blackboard via Panopto (see `Class Recordings` on the left navigation menu).