---
title: "3.4 — Multivariate OLS Estimators: Bias, Precision, and Fit — Class Notes"
citeproc: false
bibliography: ../../static/bib/references.bib
csl: ../../static/bib/chicago-syllabus-no-bib.csl
output:
  blogdown::html_page:
    template: ../../pandoc/toc-title_html.template
    toc: true
editor_options: 
  chunk_output_type: console
---

*Thursday, October 15, 2020* 

# Overview

Today we continue looking at multivariate regression, and see how the introduction of additional variables affects our model: the interpretation of the marginal effects (and we will measure an example of omitted variable bias), the standard errors of the estimators, and the goodness of fit of the regression.

We continue the extended example about class sizes and test scores, which comes from a (Stata) dataset from an old textbook that I used to use, [Stock and Watson, 2007](https://www.pearson.com/us/higher-education/product/Stock-Introduction-to-Econometrics-Update-3rd-Edition/9780133486872.html?tab=resources). Download and follow along with the data from today's example:^[Note this is a `.dta` Stata file. You will need to (install and) load the package `haven` to `read_dta()` Stata files into a dataframe.]

- [<i class="fas fa-table"></i> `caschool.dta`](http://metricsf20.classes.ryansafner.com/data/caschool.dta)

I have also made a RStudio Cloud project documenting all of the things we have been doing with this data that may help you when you start working with regressions:

- [<i class="fas fa-cloud"></i> Class Size Regression Analysis](https://rstudio.cloud/spaces/83147/project/1611251)

# Readings

Please see [today’s suggested readings](/reading/3.4-reading).

# Slides

- [<i class="fas fa-chalkboard-teacher"></i> View Lecture Slides](/slides/3.4-slides.html)
- [<i class="fas fa-file-pdf"></i> Download as PDF](/slides/3.4-slides.pdf)

# Assignments

**Midterm exam corrections** are due to me by an emailed PDF by 11:59 PM Sunday October 18. You may redo any question you did not get full points on (*do not* do questions you did not lose points on), including bonuses. Write the correct answer and *explain* why it's the right answer (i.e. show your work, don't just write $\hat{\beta_1}$ when you wrote $\hat{\beta_1}$ on the exam.) I want you to demonstrate you are *internalizing* the answers and *learning*, not just comparing with your friends to get the correct answer. You can talk to each othjer now, and are welcome to come to my (and the TAs’) office hours to go over the exam together.

# Live Class Session on Zoom

The live class <i class="fas fa-video"></i> Zoom meeting link can be found on Blackboard (see `LIVE ZOOM MEETINGS` on the left navigation menu), starting at 11:30 AM.

If you are unable to join today's live session, or if you want to review, you can find the recording stored on Blackboard via Panopto (see `Class Recordings` on the left navigation menu).