---
title: "4.1 — Panel Data and Fixed Effects - Class Notes"
citeproc: false
bibliography: ../../static/bib/references.bib
csl: ../../static/bib/chicago-syllabus-no-bib.csl
output:
  blogdown::html_page:
    template: ../../pandoc/toc-title_html.template
    toc: true
editor_options: 
  chunk_output_type: console
---

*Tuesday, November 10, 2020*

# Overview

Today, we begin our brief look at panel data, where we track multiple individuals over time. Panel data contains its own unique challenges, because it contains a time series component for every individual, giving potential sources of bias. 

We now need to understand the third assumption about $u_i$: no autocorrelation. The errors of our observations are likely going to be correlated within each individual and within each time period. 

We can correct for these with a **fixed effects** model that isolates and absorbs some of that bias. In general, for a **two-way** fixed effects model: 

$$\widehat{\text{Y}}_{it} = \beta_0+\beta_1 \text{X}_{1it} + \beta_2 \text{X}_{2it}+\alpha_{i} + \theta_{t} + \nu_{it}$$

Each observation is an individual $i$ at time $t$ (pay attention to the subscripts). 

- Let $Y_{it}$ be our dependent variable, and $X_{1it}$ be the independent variable of interest. We would like to estimate the causal effect of $X_{1it} \rightarrow Y_{it}$.
- $\alpha_i$ is the **group fixed-effect**. It absorbs all unobservable factors that **vary by group** but **don’t change over time**.
- $\tau_t$ is the **time fixed-effect**. It absorbs all unobservable factors that **do not vary by group** but **change over time**.
- Since the fixed effects *do not* pick up factors that **_both_ vary by group _and_ change over time**, we need to include other variables that might cause $X_{1it}$ to be endogenous: hence, $X_{2it}$
- $\nu_{it}$ is the remaining (random) error term (after we have pulled $\alpha_i$ and $\tau_t$ out of $u_{it}$. 

# Slides

- [<i class="fas fa-chalkboard-teacher"></i> View Lecture Slides](/slides/4.1-slides.html)
- [<i class="fas fa-file-pdf"></i> Download as PDF](/slides/4.1-slides.pdf)

# New Packages Mentioned

- [`plm`](https://cran.r-project.org/web/packages/plm/vignettes/plmPackage.html) for working with panel data and fixed effects

Note there are several other popular packages (that I have not extensively worked with), such as [`fixest`](https://github.com/lrberge/fixest), [`lfe`](https://cran.r-project.org/web/packages/lfe/index.html).

# Assignments

[Homework 5](/assignment/05-problem-set) answers are posted on that page.

# Live Class Session on Zoom

The live class <i class="fas fa-video"></i> Zoom meeting link can be found on Blackboard (see `LIVE ZOOM MEETINGS` on the left navigation menu), starting at 11:30 AM.

If you are unable to join today's live session, or if you want to review, you can find the recording stored on Blackboard via Panopto (see `Class Recordings` on the left navigation menu).
